sudo: required

services:
  - docker

before_install:
  - docker pull fedorapython/fedora-python-tox
  - docker images

script:
  - docker run --rm -it -v $PWD:/src -w /src -e TOXENV fedorapython/fedora-python-tox

matrix:
  include:
  - env: TOXENV=py27
  - env: TOXENV=py35
  - env: TOXENV=py36
  - env: TOXENV=py37
  - env: TOXENV=py38
  - env: TOXENV=py39
  - env: TOXENV=py310
  - env: TOXENV=pypy
  - env: TOXENV=pypy3
